[package]
name = "unsafe-utilities"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Helper functions for unsafe code."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
